### ISSUE TITLE
Jumbotron video not playing/displaying properly on Mobile/Tablet

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#11]
Chrome- When the website is accessed using chrome on the tablet or a phone, the video appears correctly formatted, but is frozen on a particular clip and will not play. After waiting a few moments, the video is still frozen on that clip.  

Firefox - When I access the main page in firefox on a mobile device, the video is partially covered by the header/navbar. Also, the video is completely black and will not load.

Safari - When I access the website on safari on an iphone, the video is partially hidden by the navbar and is frozen on a particular instance in the video.

**Comment by skspiers** [comment]
Chrome Mobile: ![chrome mobile](https://cloud.githubusercontent.com/assets/12926577/12490484/d332308e-c043-11e5-87c5-92b03334a843.PNG)

**Comment by skspiers** [comment]
Firefox Mobile

![img_3032](https://cloud.githubusercontent.com/assets/12926577/12490497/e8bd53f2-c043-11e5-8133-888bd08b93cb.PNG)

**Comment by jayvachon** [comment]
nav fixed - video to be replaced by static image on mobile devices
