### ISSUE TITLE
(Mac/Chrome) Download links not working 

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#20]
When clicked, the download links for several of the resources, nothing downloads. Instead, the page refreshes. 

The download links that do not work are: 
- Community PlanIt ("file1") 
- CivicSeed ("file1") 
- Work Flow ("Work Flow Facilitation Guide" and "Work Flow Card Deck")  
- Habit@ ("Habit@ - Project Summary Report to Knight Foundation")

**Comment by johnnycrich** [comment]
@jpailthorpe please note the above projects whose Resources look to be missing/misconfigured.
