### ISSUE TITLE
Add books from all fellows 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/EL-Website#31]
Need to gather content including book covers, blurbs, purchase links, etc. for any books needing to be added.

**Comment by EGL** [comment]
I'm not sure we need to add books from fellows. Because they have a temporary affiliation, I think we should leave them out.

**Comment by jpailthorpe** [comment]
Totally your call. Does this extend to Catherine, Miranda, etc? And also does the wording of "all scholarship published by the lab" then sound misleading?

**Comment by EGL** [comment]
I changed the wording on this. We can list Catherine’s stuff, but we should limit it to faculty directors, not fellows.

On Feb 8, 2016, at 10:05 AM, Jordan Pailthorpe <notifications@github.com<mailto:notifications@github.com>> wrote:

Totally your call. Does this extend to Catherine, Miranda, etc? And also does the wording of "all scholarship published by the lab" then sound misleading?

**Comment by jpailthorpe** [comment]
Is this the case with Journal articles too? or just books?
