### ISSUE TITLE
video load time is slightly slow and noticeable without still 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/EL-Website#34]
There is a slight delay in the video loading on page load. It is pretty small (~2 seconds) but significant enough to warrant notice. 

I am pretty sure that has to do with us starting the video at different times and therefore unable to have the still shot in place before the video start moving. If you notice on Airbnb's website, the delay is there, but less noticeable due to the still. 

Could we figure out a solution to having the still and not just the black image in the background?

**Comment by johnnycrich** [comment]
This is just the video buffering. I've implemented Vimeo's API, though, to catch a video 'ready' event, which fires about at the start of this buffer, and then fade the video in over 1s. This virtually mitigates the delay.
