### ISSUE TITLE
Image that replaces video loop on home page is visualizing incorrectly

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/EL-Website#35]
for some reason the image is not centering or landing correctly on the skyline. If this is difficult for this particular shot, I suggest we change it. First lets try to fix this. 
![slack for ios upload](https://cloud.githubusercontent.com/assets/10051544/12893581/ea476ae4-ce5f-11e5-9e84-9efd54dbde5d.png)

**Comment by johnnycrich** [comment]
FYI this is not occurring for me on Android.

**Comment by jpailthorpe** [comment]
both Mariko and I got this. 

I am on a iphone 5s. Not sure what she is on. I would prefer to just do a solid color background if its hard to adjust otherwise.

**Comment by johnnycrich** [comment]
I tried a bunch of CSS tricks to try to reposition/scale it but they all look odd or make the overlay hard to read. We may need some of Aidan magic here.

**Comment by jpailthorpe** [comment]
Can we just replace with a solid color block for now? Match our blue color. Aidan is way swamped I assume, but I will ask her

**Comment by jpailthorpe** [comment]
Replaced image with solid color block to resolve this issue. In the future we might design something else.
