### ISSUE TITLE
All links from the featured project page are broken

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/EL-Website#36]
http://elab.emerson.edu/research/participation-and-engagement/city-accelerator-cohort-ii

http://elab.emerson.edu/research/games-for-social-change/unlocking-health

**Comment by jayvachon** [comment]
looks like the path just needs to be updated (still pointing to research)

**Comment by jpailthorpe** [comment]
This is also happening for projects on the CMAP page
