### ISSUE TITLE
Upriver article - Developer Newsletter 2014 link not functioning  (PC/Chrome)

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#38]
Projects > UpRiver > Developer Newsletter 2014

When the user clicks on "Developer Newsletter 2014," they are directed to a 404 error.

**Comment by johnnycrich** [comment]
This should probably be a resource, not 'news', @jpailthorpe .

**Comment by jpailthorpe** [comment]
I couldn't find this, so deleted for now. Will ping wade to see if he has the PDF we can just upload.
