### ISSUE TITLE
 "Workflow Card Deck + Resources" Missing/ Link does not work

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#39]
When the user clicks on "Workflow Card Deck + Resources," they are directed to page displaying the error pictured below:
![error](https://cloud.githubusercontent.com/assets/12926577/12925300/a9558774-cf2b-11e5-9c80-2a602cbda56f.PNG)

**Comment by johnnycrich** [comment]
@skspiers which project?

**Comment by skspiers** [comment]
Sorry, Projects > Work Flow

**Comment by jpailthorpe** [comment]
fixed
