### ISSUE TITLE
Can't change project video if original video resource is deleted or modified.

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/EL-Website#4]
After deleting/changing the resource, the project video field on the project page looks like this
![screen shot 2015-11-25 at 12 39 40 pm](https://cloud.githubusercontent.com/assets/12397944/11404787/c1aecf38-9371-11e5-9531-80e0228e2500.png)

**Comment by johnnycrich** [comment]
Shared resource reference is now removed from a project if it is deleted from CMS.
