### ISSUE TITLE
Engagement Game Guidebook 404 Error 

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#44]
Publications > (Under Guides) Engagement Game Guidebook > Purchase Link

The link leads to a 404 Error: 
![engameguide](https://cloud.githubusercontent.com/assets/12926577/12927455/4d105786-cf36-11e5-8018-619336346eab.PNG)

**Comment by jpailthorpe** [comment]
[engagement-game-guide.pdf](https://github.com/engagementgamelab/EL-Website/files/123724/engagement-game-guide.pdf)
