### ISSUE TITLE
DARG Guidebook 404 Error 

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/EL-Website#45]
Publications > (Under Guides) Darg Guidebook > Purchase Link

The link leads to a 404 Error: 
![darg guidebook](https://cloud.githubusercontent.com/assets/12926577/12927534/bc99ae40-cf36-11e5-8200-d4131d625371.PNG)

**Comment by jpailthorpe** [comment]
[darg.pdf](https://github.com/engagementgamelab/EL-Website/files/123725/darg.pdf)
