### ISSUE TITLE
Add (3) fields to the "project Information" sidebar

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/EL-Website#46]
This was a bit up in the air for a while, but we now have landed on what we will be putting in the project information field. 

_1st line _Principal Investigator: [NAME] 
_2nd line_Project Manager: [NAME] 
_3rd line_Project website: [LINK](make sure this is not a required field. Pretty sure it isn't, but some projects don't have external websites and it would be weird if this is required) 
_4th line_ Project Dates: [Start and end DATE FIELDS](leave this for now, will check if we want to keep it) 
_4th line_Executive Summary Report: [LINK]

**Comment by johnnycrich** [comment]
@jpailthorpe are any of these going to be required for _every_ project?
