### ISSUE TITLE
CMAP Program - Add a link to the top field on the program page

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/EL-Website#48]
Link http://www.emerson.edu/academics/graduate-degrees to text "APPLY NOW" in the first block of text on this page. Needs to be hard coded by @johnnycrich 

![screen shot 2016-02-10 at 3 43 46 pm](https://cloud.githubusercontent.com/assets/11759152/12961160/04a86a38-d00d-11e5-9ef9-3212363a050f.png)

**Comment by johnnycrich** [comment]
Done!
